"""CLI command for pseudo-label generation from diagnostic caches."""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path

import click
import cv2
import numpy as np

from aquapose.training.coco_interchange import write_coco_keypoints
from aquapose.training.common import _LutConfigFromDict
from aquapose.training.geometry import (
    affine_warp_crop,
    format_pose_annotation,
    pca_obb,
    transform_keypoints,
)
from aquapose.training.pseudo_labels import (
    compute_curvature,
    detect_gaps,
    generate_fish_labels,
    generate_gap_fish_labels,
)

logger = logging.getLogger(__name__)


@dataclass
class PseudoLabelConfig:
    """Configuration for pseudo-label generation."""

    lateral_ratio: float = 0.18
    max_camera_residual_px: float = 15.0


@click.group("pseudo-label")
def pseudo_label_group() -> None:
    """Pseudo-label generation from pipeline diagnostic caches."""


@pseudo_label_group.command("generate")
@click.argument("run", default=None, required=False)
@click.option(
    "--lateral-ratio",
    type=float,
    default=0.18,
    show_default=True,
    help="OBB lateral padding as fraction of fish arc length.",
)
@click.option(
    "--max-camera-residual",
    type=float,
    default=15.0,
    show_default=True,
    help="Per-camera residual threshold in pixels (consensus only).",
)
@click.option(
    "--skip-gaps",
    is_flag=True,
    default=False,
    help="Skip gap-fill label generation (use when InverseLUT/detections/tracks unavailable).",
)
@click.option(
    "--min-cameras",
    type=int,
    default=3,
    show_default=True,
    help="Minimum contributing cameras before gap detection activates.",
)
@click.option(
    "--crop-width",
    type=int,
    default=128,
    show_default=True,
    help="Pose crop width in pixels.",
)
@click.option(
    "--crop-height",
    type=int,
    default=64,
    show_default=True,
    help="Pose crop height in pixels.",
)
@click.option(
    "--temporal-step",
    type=int,
    default=1,
    show_default=True,
    help="Process every Nth frame (1 = all frames).",
)
@click.option(
    "--min-visible-ratio",
    type=float,
    default=0.67,
    show_default=True,
    help="Minimum fraction of keypoints that must be visible (rounded to nearest integer).",
)
@click.option(
    "--viz",
    is_flag=True,
    default=False,
    help="Generate inspection visualizations after label generation.",
)
@click.pass_context
def generate(
    ctx: click.Context,
    run: str | None,
    lateral_ratio: float,
    max_camera_residual: float,
    skip_gaps: bool,
    min_cameras: int,
    crop_width: int,
    crop_height: int,
    temporal_step: int,
    min_visible_ratio: float,
    viz: bool,
) -> None:
    """Generate YOLO OBB and pose pseudo-labels from diagnostic caches.

    Reads a pipeline run's frozen config, loads diagnostic caches containing
    3D midline reconstructions, reprojects them into camera views, extracts
    video frames, and writes YOLO-standard OBB and pose datasets.

    Always generates consensus labels. Gap-fill labels are generated by
    default unless ``--skip-gaps`` is specified.
    """
    from aquapose.cli_utils import get_project_dir, resolve_run

    gaps = not skip_gaps

    # Dynamic imports to avoid training->engine import boundary violation
    import importlib

    _engine_config = importlib.import_module("aquapose.engine.config")
    load_config = _engine_config.load_config

    from aquapose.calibration.loader import (
        compute_undistortion_maps,
        load_calibration_data,
    )
    from aquapose.calibration.projection import RefractiveProjectionModel
    from aquapose.core.types.frame_source import VideoFrameSource
    from aquapose.evaluation.runner import load_run_context

    # 1. Resolve run dir and load frozen config
    run_dir = resolve_run(run, get_project_dir(ctx))
    config_path = run_dir / "config.yaml"
    if not config_path.exists():
        raise click.ClickException(
            f"config.yaml not found in {run_dir}. "
            "This run directory does not contain a frozen config."
        )
    pipeline_config = load_config(yaml_path=str(config_path))

    # 2. Fail fast if keypoint_t_values not configured
    keypoint_t_values = pipeline_config.pose.keypoint_t_values
    if keypoint_t_values is None:
        raise click.ClickException(
            "keypoint_t_values is None in config. "
            "Run 'aquapose prep calibrate-keypoints' first to set t-values."
        )

    # 4. Load diagnostic caches
    context, _metadata = load_run_context(run_dir)
    if context is None:
        raise click.ClickException(
            f"No diagnostic caches found in {run_dir}/diagnostics/. "
            "Run the pipeline with --add-observer diagnostic first."
        )

    if context.midlines_3d is None:
        raise click.ClickException(
            "Diagnostic caches contain no 3D midline reconstructions."
        )

    # Fail fast for gaps: need detections and tracks_2d
    if gaps:
        if context.detections is None:
            raise click.ClickException(
                "Diagnostic caches contain no detections. "
                "Gap detection requires detection data."
            )
        if context.tracks_2d is None:
            raise click.ClickException(
                "Diagnostic caches contain no 2D tracks. "
                "Gap detection requires tracking data."
            )

    # 5. Load calibration
    calibration = load_calibration_data(pipeline_config.calibration_path)

    # 6. Build projection models per camera (using undistorted K_new)
    proj_models: dict[str, RefractiveProjectionModel] = {}
    for cam_id in calibration.ring_cameras:
        cam = calibration.cameras[cam_id]
        undist_maps = compute_undistortion_maps(cam)
        proj_models[cam_id] = RefractiveProjectionModel(
            K=undist_maps.K_new,
            R=cam.R,
            t=cam.t,
            water_z=calibration.water_z,
            normal=calibration.interface_normal,
            n_air=calibration.n_air,
            n_water=calibration.n_water,
        )

    # 7. Load InverseLUT if gaps mode is active
    inverse_lut = None
    if gaps:
        _luts_mod = importlib.import_module("aquapose.calibration.luts")
        load_inverse_luts = _luts_mod.load_inverse_luts

        # Build LUT config from frozen config's lut section
        lut_raw = pipeline_config.lut.__dict__
        lut_config = _LutConfigFromDict(lut_raw)
        inverse_lut = load_inverse_luts(pipeline_config.calibration_path, lut_config)
        if inverse_lut is None:
            raise click.ClickException(
                "Failed to load InverseLUT. Run 'aquapose prep generate-luts' first."
            )

    # 7b. Build frame-to-tracklet index (needed for completeness filter)
    frame_tracklet_index: dict[str, dict[int, list]] | None = None
    if context.tracks_2d is not None:
        frame_tracklet_index = {}
        for cam_id, tracklets in context.tracks_2d.items():
            cam_index: dict[int, list] = {}
            for tracklet in tracklets:
                for frame_i in tracklet.frames:
                    cam_index.setdefault(frame_i, []).append(tracklet)
            frame_tracklet_index[cam_id] = cam_index

    # 8. Create output directories
    pseudo_dir = run_dir / "pseudo_labels"

    # Merged OBB directory
    obb_images_dir = pseudo_dir / "obb" / "images" / "train"
    obb_labels_dir = pseudo_dir / "obb" / "labels" / "train"
    for d in [obb_images_dir, obb_labels_dir]:
        d.mkdir(parents=True, exist_ok=True)

    # Consensus pose directory
    cons_pose_images = pseudo_dir / "pose" / "consensus" / "images" / "train"
    cons_pose_labels = pseudo_dir / "pose" / "consensus" / "labels" / "train"
    for d in [cons_pose_images, cons_pose_labels]:
        d.mkdir(parents=True, exist_ok=True)

    # Gap pose directory (only when gaps enabled)
    gap_pose_images = pseudo_dir / "pose" / "gap" / "images" / "train"
    gap_pose_labels = pseudo_dir / "pose" / "gap" / "labels" / "train"
    if gaps:
        for d in [gap_pose_images, gap_pose_labels]:
            d.mkdir(parents=True, exist_ok=True)

    # 9. Iterate frames and generate labels
    obb_confidence: dict[str, dict] = {}
    cons_pose_confidence: dict[str, dict] = {}
    gap_pose_confidence: dict[str, dict] = {}
    obb_images_count = 0
    obb_labels_count = 0
    obb_skipped_incomplete = 0
    cons_pose_count = 0
    gap_pose_count = 0
    obb_confidence_values: list[float] = []

    n_keypoints = len(keypoint_t_values)
    min_visible = max(1, round(min_visible_ratio * n_keypoints))
    click.echo(
        f"Min visible keypoints: {min_visible}/{n_keypoints} "
        f"(ratio {min_visible_ratio:.2f})"
    )

    with VideoFrameSource(
        pipeline_config.video_dir,
        pipeline_config.calibration_path,
    ) as frame_source:
        n_frames = len(context.midlines_3d)
        n_selected = (
            (n_frames + temporal_step - 1) // temporal_step
            if temporal_step > 1
            else n_frames
        )
        step_msg = f" (every {temporal_step}th)" if temporal_step > 1 else ""
        click.echo(
            f"Processing {n_selected}/{n_frames} frames{step_msg} across {len(proj_models)} cameras..."
        )
        click.echo("  Generating consensus (Source A) labels")
        if gaps:
            click.echo("  Generating gap (Source B) labels")

        for frame_idx, fish_dict in enumerate(context.midlines_3d):
            if not fish_dict:
                continue

            if temporal_step > 1 and frame_idx % temporal_step != 0:
                continue

            # Collect ALL labels per camera into unified dicts
            # OBB labels are merged (consensus + gap) for completeness filtering
            obb_labels: dict[str, dict] = {}
            cons_pose_data: dict[str, list[dict]] = {}
            gap_pose_data: dict[str, list[dict]] = {}

            for fish_id, midline in fish_dict.items():
                # --- Consensus path (always runs) ---
                if midline.per_camera_residuals is not None:
                    for cam_id in midline.per_camera_residuals:
                        if cam_id not in proj_models:
                            continue

                        cam_data = calibration.cameras[cam_id]
                        img_w, img_h = cam_data.image_size

                        result = generate_fish_labels(
                            midline=midline,
                            projection_model=proj_models[cam_id],
                            img_w=img_w,
                            img_h=img_h,
                            keypoint_t_values=keypoint_t_values,
                            lateral_ratio=lateral_ratio,
                            max_camera_residual_px=max_camera_residual,
                            camera_id=cam_id,
                            min_visible_keypoints=min_visible,
                        )

                        if result is None:
                            continue

                        if cam_id not in obb_labels:
                            obb_labels[cam_id] = {
                                "obb_lines": [],
                                "conf_entries": [],
                            }
                        obb_labels[cam_id]["obb_lines"].append(result["obb_line"])
                        obb_labels[cam_id]["conf_entries"].append(
                            {
                                "fish_id": int(fish_id),
                                "confidence": result["confidence"],
                                "raw_metrics": result["raw_metrics"],
                                "source": "consensus",
                                "curvature_3d": compute_curvature(
                                    midline.control_points
                                ),
                            }
                        )

                        if "pose_line" in result:
                            cons_pose_data.setdefault(cam_id, []).append(
                                {
                                    "keypoints_2d": result["keypoints_2d"],
                                    "visibility": result["visibility"],
                                    "lateral_pad": result["lateral_pad"],
                                    "fish_id": int(fish_id),
                                    "confidence": result["confidence"],
                                    "raw_metrics": result["raw_metrics"],
                                }
                            )

                # --- Gap path ---
                if gaps and inverse_lut is not None:
                    frame_tracks_for_frame: dict[str, list] = {}
                    assert frame_tracklet_index is not None
                    for cam_id_t, cam_index in frame_tracklet_index.items():
                        tracklets_at_frame = cam_index.get(frame_idx, [])
                        if tracklets_at_frame:
                            frame_tracks_for_frame[cam_id_t] = tracklets_at_frame

                    frame_dets = (
                        context.detections[frame_idx]
                        if context.detections is not None
                        else {}
                    )

                    gap_list = detect_gaps(
                        midline,
                        inverse_lut,
                        proj_models,
                        frame_dets,
                        frame_tracks_for_frame,
                        min_cameras=min_cameras,
                    )

                    for cam_id, reason in gap_list:
                        if cam_id not in proj_models:
                            continue

                        cam_data = calibration.cameras[cam_id]
                        img_w, img_h = cam_data.image_size

                        gap_result = generate_gap_fish_labels(
                            midline=midline,
                            projection_model=proj_models[cam_id],
                            img_w=img_w,
                            img_h=img_h,
                            keypoint_t_values=keypoint_t_values,
                            lateral_ratio=lateral_ratio,
                            min_visible_keypoints=min_visible,
                        )

                        if gap_result is None:
                            continue

                        if cam_id not in obb_labels:
                            obb_labels[cam_id] = {
                                "obb_lines": [],
                                "conf_entries": [],
                            }
                        obb_labels[cam_id]["obb_lines"].append(gap_result["obb_line"])
                        obb_labels[cam_id]["conf_entries"].append(
                            {
                                "fish_id": int(fish_id),
                                "confidence": gap_result["confidence"],
                                "raw_metrics": gap_result["raw_metrics"],
                                "source": "gap",
                                "gap_reason": reason,
                                "n_source_cameras": midline.n_cameras,
                                "curvature_3d": compute_curvature(
                                    midline.control_points
                                ),
                            }
                        )

                        if "pose_line" in gap_result:
                            gap_pose_data.setdefault(cam_id, []).append(
                                {
                                    "keypoints_2d": gap_result["keypoints_2d"],
                                    "visibility": gap_result["visibility"],
                                    "lateral_pad": gap_result["lateral_pad"],
                                    "fish_id": int(fish_id),
                                    "confidence": gap_result["confidence"],
                                    "raw_metrics": gap_result["raw_metrics"],
                                    "gap_reason": reason,
                                    "n_source_cameras": midline.n_cameras,
                                }
                            )

            # Determine which cameras need frame images
            cams_needing_frames = (
                set(obb_labels.keys())
                | set(cons_pose_data.keys())
                | set(gap_pose_data.keys())
            )
            if not cams_needing_frames:
                continue

            # Read frame images once
            try:
                frames = frame_source.read_frame(frame_idx)
            except Exception:
                logger.warning("Failed to read frame %d, skipping", frame_idx)
                continue

            # Write per-camera outputs
            for cam_id in cams_needing_frames:
                if cam_id not in frames:
                    continue

                image_name = f"{frame_idx:06d}_{cam_id}"

                # --- Merged OBB with completeness filter ---
                cam_obb = obb_labels.get(cam_id)
                if cam_obb:
                    n_labeled = len(cam_obb["obb_lines"])
                    n_tracked = _count_detected_tracklets(
                        frame_tracklet_index, cam_id, frame_idx
                    )

                    # Completeness check: skip if not all tracked fish are labeled
                    if n_tracked > 0 and n_labeled < n_tracked:
                        obb_skipped_incomplete += 1
                    else:
                        cv2.imwrite(
                            str(obb_images_dir / f"{image_name}.jpg"), frames[cam_id]
                        )
                        (obb_labels_dir / f"{image_name}.txt").write_text(
                            "\n".join(cam_obb["obb_lines"]) + "\n"
                        )
                        obb_confidence[image_name] = {
                            "labels": cam_obb["conf_entries"],
                            "tracked_fish_count": n_tracked,
                            "complete": True,
                        }
                        obb_images_count += 1
                        obb_labels_count += n_labeled
                        for entry in cam_obb["conf_entries"]:
                            obb_confidence_values.append(entry["confidence"])

                # --- Consensus pose crops ---
                if cam_id in cons_pose_data:
                    fish_data_for_crop = [
                        {
                            "keypoints_2d": fd["keypoints_2d"],
                            "visibility": fd["visibility"],
                            "lateral_pad": fd["lateral_pad"],
                            "fish_id": fd["fish_id"],
                        }
                        for fd in cons_pose_data[cam_id]
                    ]
                    _write_pose_crops(
                        frame=frames[cam_id],
                        fish_data_list=fish_data_for_crop,
                        frame_idx=frame_idx,
                        cam_id=cam_id,
                        crop_w=crop_width,
                        crop_h=crop_height,
                        pose_images_dir=cons_pose_images,
                        pose_labels_dir=cons_pose_labels,
                        min_visible=min_visible,
                    )
                    for fd in cons_pose_data[cam_id]:
                        crop_stem = f"{frame_idx:06d}_{cam_id}"
                        if crop_stem not in cons_pose_confidence:
                            cons_pose_confidence[crop_stem] = {"labels": []}
                        vis_mask = fd["visibility"] > 0
                        vis_kpts = fd["keypoints_2d"][vis_mask]
                        cons_pose_confidence[crop_stem]["labels"].append(
                            {
                                "fish_id": fd["fish_id"],
                                "confidence": fd["confidence"],
                                "raw_metrics": fd["raw_metrics"],
                                "curvature_2d": float(compute_curvature(vis_kpts))
                                if len(vis_kpts) >= 3
                                else 0.0,
                            }
                        )
                    cons_pose_count += len(cons_pose_data[cam_id])

                # --- Gap pose crops ---
                if gaps and cam_id in gap_pose_data:
                    fish_data_for_crop = [
                        {
                            "keypoints_2d": fd["keypoints_2d"],
                            "visibility": fd["visibility"],
                            "lateral_pad": fd["lateral_pad"],
                            "fish_id": fd["fish_id"],
                        }
                        for fd in gap_pose_data[cam_id]
                    ]
                    _write_pose_crops(
                        frame=frames[cam_id],
                        fish_data_list=fish_data_for_crop,
                        frame_idx=frame_idx,
                        cam_id=cam_id,
                        crop_w=crop_width,
                        crop_h=crop_height,
                        pose_images_dir=gap_pose_images,
                        pose_labels_dir=gap_pose_labels,
                        min_visible=min_visible,
                    )
                    for fd in gap_pose_data[cam_id]:
                        crop_stem = f"{frame_idx:06d}_{cam_id}"
                        if crop_stem not in gap_pose_confidence:
                            gap_pose_confidence[crop_stem] = {"labels": []}
                        gap_pose_confidence[crop_stem]["labels"].append(
                            {
                                "fish_id": fd["fish_id"],
                                "confidence": fd["confidence"],
                                "raw_metrics": fd["raw_metrics"],
                                "gap_reason": fd["gap_reason"],
                                "n_source_cameras": fd["n_source_cameras"],
                            }
                        )
                    gap_pose_count += len(gap_pose_data[cam_id])

            if (frame_idx + 1) % 100 == 0:
                click.echo(f"  Frame {frame_idx + 1}/{n_frames}...")

    # 10. Write dataset.yaml and confidence.json
    # OBB (merged)
    _write_obb_dataset_yaml(pseudo_dir / "obb")
    _write_confidence_json(pseudo_dir / "obb", obb_confidence)

    # Pose consensus
    _write_pose_dataset_yaml(pseudo_dir / "pose" / "consensus", n_keypoints)
    _write_confidence_json(pseudo_dir / "pose" / "consensus", cons_pose_confidence)
    write_coco_keypoints(pseudo_dir / "pose" / "consensus", n_keypoints)

    # Pose gap
    if gaps:
        _write_pose_dataset_yaml(pseudo_dir / "pose" / "gap", n_keypoints)
        _write_confidence_json(pseudo_dir / "pose" / "gap", gap_pose_confidence)
        write_coco_keypoints(pseudo_dir / "pose" / "gap", n_keypoints)

    # 11. Print summary
    click.echo("\nPseudo-label generation complete.")
    mean_conf = float(np.mean(obb_confidence_values)) if obb_confidence_values else 0.0
    click.echo(
        f"  OBB: {obb_images_count} images, {obb_labels_count} labels, "
        f"mean confidence {mean_conf:.3f}, {obb_skipped_incomplete} skipped (incomplete)"
    )
    click.echo(f"  Pose (consensus): {cons_pose_count} crops")
    if gaps:
        click.echo(f"  Pose (gap): {gap_pose_count} crops")
    click.echo(f"  Output: {pseudo_dir}")

    if viz:
        viz_dir = pseudo_dir / "viz"
        viz_targets: list[tuple[Path, Path]] = [
            (pseudo_dir / "obb", viz_dir / "obb"),
            (pseudo_dir / "pose" / "consensus", viz_dir / "pose" / "consensus"),
        ]
        if gaps:
            viz_targets.append((pseudo_dir / "pose" / "gap", viz_dir / "pose" / "gap"))
        click.echo("\nGenerating inspection visualizations...")
        for data_path, out_path in viz_targets:
            images_check = data_path / "images" / "train"
            if not images_check.exists() or not any(images_check.iterdir()):
                continue
            _inspect_subset(data_path, out_path, n_samples=None, seed=42)


def _write_pose_crops(
    frame: np.ndarray,
    fish_data_list: list[dict],
    frame_idx: int,
    cam_id: str,
    crop_w: int,
    crop_h: int,
    pose_images_dir: Path,
    pose_labels_dir: Path,
    min_visible: int = 2,
) -> None:
    """Write per-fish OBB crop images and crop-space pose labels.

    For each fish (the "primary"), computes the OBB from its keypoints
    using per-fish ``lateral_pad``, warps the frame to crop space, then
    collects pose annotations for ALL fish visible in that crop
    (multi-fish-per-crop logic matching the manual annotation pipeline).

    Args:
        frame: Full-frame BGR image.
        fish_data_list: List of dicts with ``keypoints_2d``, ``visibility``,
            ``lateral_pad``, ``fish_id`` for each fish in this camera view.
        frame_idx: Frame index (for filename).
        cam_id: Camera identifier (for filename).
        crop_w: Output crop width in pixels.
        crop_h: Output crop height in pixels.
        pose_images_dir: Output directory for crop images.
        pose_labels_dir: Output directory for crop label files.
        min_visible: Minimum visible keypoints for a fish to appear in crop.
    """
    for fish_idx, primary in enumerate(fish_data_list):
        kp_primary = primary["keypoints_2d"]
        vis_primary = primary["visibility"]
        primary_lateral_pad = primary["lateral_pad"]

        # Compute OBB for the primary fish in image space
        obb_corners = pca_obb(kp_primary, vis_primary, primary_lateral_pad)

        # Warp frame to crop
        warped, affine_mat = affine_warp_crop(frame, obb_corners, crop_w, crop_h)

        # Collect pose annotations for all fish visible in this crop
        pose_rows: list[str] = []
        for other in fish_data_list:
            kp_crop, vis_crop = transform_keypoints(
                other["keypoints_2d"],
                other["visibility"],
                affine_mat,
                crop_w,
                crop_h,
            )
            if int(vis_crop.sum()) < min_visible:
                continue

            # Compute PCA OBB on crop-space keypoints for the bbox
            other_lateral_pad = other["lateral_pad"]
            crop_obb = pca_obb(kp_crop, vis_crop, other_lateral_pad)
            crop_obb[:, 0] = np.clip(crop_obb[:, 0], 0, crop_w - 1)
            crop_obb[:, 1] = np.clip(crop_obb[:, 1], 0, crop_h - 1)
            x_min, y_min = crop_obb.min(axis=0)
            x_max, y_max = crop_obb.max(axis=0)
            cx = (x_min + x_max) / 2.0 / crop_w
            cy = (y_min + y_max) / 2.0 / crop_h
            bw = (x_max - x_min) / crop_w
            bh = (y_max - y_min) / crop_h

            row = format_pose_annotation(
                cx, cy, bw, bh, kp_crop, vis_crop, crop_w, crop_h
            )
            pose_rows.append(" ".join(str(v) for v in row))

        if not pose_rows:
            continue

        crop_stem = f"{frame_idx:06d}_{cam_id}_{fish_idx:03d}"
        cv2.imwrite(str(pose_images_dir / f"{crop_stem}.jpg"), warped)
        (pose_labels_dir / f"{crop_stem}.txt").write_text("\n".join(pose_rows) + "\n")


def _count_detected_tracklets(
    frame_tracklet_index: dict[str, dict[int, list]] | None,
    cam_id: str,
    frame_idx: int,
) -> int:
    """Count tracklets with 'detected' status at a given frame.

    Args:
        frame_tracklet_index: Pre-built frame-to-tracklet index per camera.
            None if tracking data is unavailable.
        cam_id: Camera identifier.
        frame_idx: Frame index.

    Returns:
        Number of tracklets with detected status. Returns 0 if index is None
        or camera/frame not found (disabling completeness filtering).
    """
    if frame_tracklet_index is None:
        return 0
    cam_index = frame_tracklet_index.get(cam_id, {})
    tracklets = cam_index.get(frame_idx, [])
    count = 0
    for tracklet in tracklets:
        try:
            idx = tracklet.frames.index(frame_idx)
        except ValueError:
            continue
        if tracklet.frame_status[idx] == "detected":
            count += 1
    return count


def _write_obb_dataset_yaml(obb_dir: Path) -> None:
    """Write OBB dataset.yaml."""
    obb_dataset = {
        "path": str(obb_dir),
        "train": "images/train",
        "nc": 1,
        "names": {0: "fish"},
    }
    (obb_dir / "dataset.yaml").write_text(_yaml_dump(obb_dataset), encoding="utf-8")


def _write_pose_dataset_yaml(pose_dir: Path, n_keypoints: int) -> None:
    """Write pose dataset.yaml."""
    flip_idx = list(range(n_keypoints))
    pose_dataset = {
        "path": str(pose_dir),
        "train": "images/train",
        "nc": 1,
        "names": {0: "fish"},
        "kpt_shape": [n_keypoints, 3],
        "flip_idx": flip_idx,
    }
    (pose_dir / "dataset.yaml").write_text(_yaml_dump(pose_dataset), encoding="utf-8")


def _write_confidence_json(
    subset_dir: Path,
    confidence_sidecar: dict[str, dict],
) -> None:
    """Write confidence.json sidecar for a subset directory."""
    confidence_path = subset_dir / "confidence.json"
    confidence_path.write_text(
        json.dumps(confidence_sidecar, indent=2), encoding="utf-8"
    )


def _yaml_dump(data: dict) -> str:
    """Dump dict to YAML string."""
    import yaml

    return yaml.dump(data, default_flow_style=False, sort_keys=False)


@pseudo_label_group.command("mine-hard")
@click.argument("run", default=None, required=False)
@click.option(
    "--categories",
    type=click.Choice(
        ["tracking_gaps", "low_cameras", "high_curvature", "high_residual"],
        case_sensitive=False,
    ),
    multiple=True,
    default=None,
    help="Categories to mine. Default: all four.",
)
@click.option(
    "--max-cameras",
    type=int,
    default=2,
    show_default=True,
    help="Threshold for low_cameras: fish seen by <= this many cameras.",
)
@click.option(
    "--min-gap-length",
    type=int,
    default=1,
    show_default=True,
    help="Minimum consecutive coasted frames for tracking_gaps category.",
)
@click.option(
    "--curvature-percentile",
    type=float,
    default=95.0,
    show_default=True,
    help="Percentile threshold for high_curvature category.",
)
@click.option(
    "--residual-percentile",
    type=float,
    default=95.0,
    show_default=True,
    help="Percentile threshold for high_residual category.",
)
@click.option(
    "--curvature-threshold",
    type=float,
    default=None,
    help="Absolute curvature threshold (overrides percentile).",
)
@click.option(
    "--residual-threshold",
    type=float,
    default=None,
    help="Absolute residual threshold in pixels (overrides percentile).",
)
@click.option(
    "--temporal-step",
    type=int,
    default=1,
    show_default=True,
    help="Process every Nth frame.",
)
@click.option(
    "--max-per-category",
    type=int,
    default=None,
    help="Maximum examples per category.",
)
@click.option(
    "--lateral-ratio",
    type=float,
    default=0.18,
    show_default=True,
    help="OBB lateral padding as fraction of fish arc length.",
)
@click.option(
    "--max-camera-residual",
    type=float,
    default=15.0,
    show_default=True,
    help="Per-camera residual threshold in pixels for consensus labels.",
)
@click.option(
    "--crop-width",
    type=int,
    default=128,
    show_default=True,
    help="Pose crop width in pixels.",
)
@click.option(
    "--crop-height",
    type=int,
    default=64,
    show_default=True,
    help="Pose crop height in pixels.",
)
@click.pass_context
def mine_hard(
    ctx: click.Context,
    run: str | None,
    categories: tuple[str, ...] | None,
    max_cameras: int,
    min_gap_length: int,
    curvature_percentile: float,
    residual_percentile: float,
    curvature_threshold: float | None,
    residual_threshold: float | None,
    temporal_step: int,
    max_per_category: int | None,
    lateral_ratio: float,
    max_camera_residual: float,
    crop_width: int,
    crop_height: int,
) -> None:
    """Mine hard examples from pipeline results for manual annotation.

    Identifies four categories of hard examples from a pipeline run's
    diagnostic caches and writes them as YOLO-format datasets for manual
    annotation:

    \b
    - tracking_gaps: per-camera frames where detector missed a tracked fish (OBB)
    - low_cameras: fish seen by few cameras, filtered by geometric visibility (OBB)
    - high_curvature: extreme body bends (pose crops)
    - high_residual: high reprojection error (pose crops)
    """
    import importlib

    from aquapose.cli_utils import get_project_dir, resolve_run

    _engine_config = importlib.import_module("aquapose.engine.config")
    load_config = _engine_config.load_config

    from aquapose.calibration.loader import (
        compute_undistortion_maps,
        load_calibration_data,
    )
    from aquapose.calibration.projection import RefractiveProjectionModel
    from aquapose.core.types.frame_source import VideoFrameSource
    from aquapose.evaluation.runner import load_run_context
    from aquapose.training.hard_mining import (
        compute_thresholds,
        mine_high_curvature,
        mine_high_residual,
        mine_low_cameras,
        mine_tracking_gaps,
    )

    all_categories = {"tracking_gaps", "low_cameras", "high_curvature", "high_residual"}
    active = set(categories) if categories else all_categories

    # 1. Resolve run and load config
    run_dir = resolve_run(run, get_project_dir(ctx))
    config_path = run_dir / "config.yaml"
    if not config_path.exists():
        raise click.ClickException(f"config.yaml not found in {run_dir}.")
    pipeline_config = load_config(yaml_path=str(config_path))

    keypoint_t_values = pipeline_config.pose.keypoint_t_values
    if keypoint_t_values is None:
        raise click.ClickException(
            "keypoint_t_values is None. Run 'aquapose prep calibrate-keypoints' first."
        )

    # 2. Load diagnostic caches
    context, _metadata = load_run_context(run_dir)
    if context is None or context.midlines_3d is None:
        raise click.ClickException(
            f"No diagnostic caches with 3D midlines found in {run_dir}/diagnostics/."
        )

    midlines_3d = context.midlines_3d

    # Fail fast: tracking_gaps needs tracks_2d
    if "tracking_gaps" in active and context.tracks_2d is None:
        raise click.ClickException(
            "Diagnostic caches contain no 2D tracks. "
            "tracking_gaps requires tracking data."
        )

    # 3. Load calibration and build projection models
    calibration = load_calibration_data(pipeline_config.calibration_path)
    proj_models: dict[str, RefractiveProjectionModel] = {}
    for cam_id in calibration.ring_cameras:
        cam = calibration.cameras[cam_id]
        undist_maps = compute_undistortion_maps(cam)
        proj_models[cam_id] = RefractiveProjectionModel(
            K=undist_maps.K_new,
            R=cam.R,
            t=cam.t,
            water_z=calibration.water_z,
            normal=calibration.interface_normal,
            n_air=calibration.n_air,
            n_water=calibration.n_water,
        )

    # 4. Load InverseLUT if low_cameras is active
    inverse_lut = None
    if "low_cameras" in active:
        _luts_mod = importlib.import_module("aquapose.calibration.luts")
        load_inverse_luts = _luts_mod.load_inverse_luts
        lut_raw = pipeline_config.lut.__dict__
        lut_config = _LutConfigFromDict(lut_raw)
        inverse_lut = load_inverse_luts(pipeline_config.calibration_path, lut_config)
        if inverse_lut is None:
            raise click.ClickException(
                "Failed to load InverseLUT. Run 'aquapose prep generate-luts' first."
            )

    # 5. Compute thresholds
    need_thresholds = active & {"high_curvature", "high_residual"}
    if need_thresholds:
        curv_thresh, resid_thresh = compute_thresholds(
            midlines_3d,
            curvature_percentile=curvature_percentile,
            residual_percentile=residual_percentile,
        )
        if curvature_threshold is not None:
            curv_thresh = curvature_threshold
        if residual_threshold is not None:
            resid_thresh = residual_threshold
        click.echo(
            f"Thresholds: curvature={curv_thresh:.4f}, residual={resid_thresh:.2f}px"
        )
    else:
        curv_thresh = 0.0
        resid_thresh = 0.0

    # 6. Run mining
    tracking_gap_examples = (
        mine_tracking_gaps(
            context.tracks_2d,
            temporal_step=temporal_step,
            max_examples=max_per_category,
            min_gap_length=min_gap_length,
        )
        if "tracking_gaps" in active and context.tracks_2d is not None
        else []
    )
    low_cameras_examples = (
        mine_low_cameras(
            midlines_3d,
            inverse_lut=inverse_lut,
            max_cameras=max_cameras,
            temporal_step=temporal_step,
            max_examples=max_per_category,
        )
        if "low_cameras" in active and inverse_lut is not None
        else []
    )
    high_curvature_examples = (
        mine_high_curvature(
            midlines_3d,
            curvature_threshold=curv_thresh,
            temporal_step=temporal_step,
            max_examples=max_per_category,
        )
        if "high_curvature" in active
        else []
    )
    high_residual_examples = (
        mine_high_residual(
            midlines_3d,
            residual_threshold=resid_thresh,
            temporal_step=temporal_step,
            max_examples=max_per_category,
        )
        if "high_residual" in active
        else []
    )

    click.echo(
        f"\nMined: {len(tracking_gap_examples)} tracking_gaps, "
        f"{len(low_cameras_examples)} low_cameras, "
        f"{len(high_curvature_examples)} high_curvature, "
        f"{len(high_residual_examples)} high_residual"
    )

    total = (
        len(tracking_gap_examples)
        + len(low_cameras_examples)
        + len(high_curvature_examples)
        + len(high_residual_examples)
    )
    if total == 0:
        click.echo("No hard examples found.")
        return

    # 7. Create output directories
    hard_dir = run_dir / "pseudo_labels" / "hard"
    cat_dirs: dict[str, tuple[Path, Path]] = {}
    for cat in active:
        img_dir = hard_dir / cat / "images" / "train"
        lbl_dir = hard_dir / cat / "labels" / "train"
        img_dir.mkdir(parents=True, exist_ok=True)
        lbl_dir.mkdir(parents=True, exist_ok=True)
        cat_dirs[cat] = (img_dir, lbl_dir)

    # 8. Build frame dispatch map
    frame_dispatch: dict[int, dict[str, list]] = {}
    for ex in tracking_gap_examples:
        frame_dispatch.setdefault(ex.frame_idx, {}).setdefault(
            "tracking_gaps", []
        ).append(ex)
    for ex in low_cameras_examples:
        frame_dispatch.setdefault(ex.frame_idx, {}).setdefault(
            "low_cameras", []
        ).append(ex)
    for ex in high_curvature_examples:
        frame_dispatch.setdefault(ex.frame_idx, {}).setdefault(
            "high_curvature", []
        ).append(ex)
    for ex in high_residual_examples:
        frame_dispatch.setdefault(ex.frame_idx, {}).setdefault(
            "high_residual", []
        ).append(ex)

    # 9. Iterate frames and write outputs
    n_keypoints = len(keypoint_t_values)
    min_visible = max(1, round(0.67 * n_keypoints))
    all_camera_ids = sorted(proj_models.keys())
    n_written: dict[str, int] = {cat: 0 for cat in active}

    click.echo(f"Writing outputs for {len(frame_dispatch)} unique frames...")

    with VideoFrameSource(
        pipeline_config.video_dir,
        pipeline_config.calibration_path,
    ) as frame_source:
        for frame_idx in sorted(frame_dispatch):
            frames = frame_source.read_frame(frame_idx)
            cats_for_frame = frame_dispatch[frame_idx]
            fish_dict = midlines_3d[frame_idx] if frame_idx < len(midlines_3d) else {}

            # --- tracking_gaps: specific camera only, partial OBB labels ---
            if "tracking_gaps" in cats_for_frame:
                img_dir, lbl_dir = cat_dirs["tracking_gaps"]
                for ex in cats_for_frame["tracking_gaps"]:
                    cam_id = ex.camera_id
                    if cam_id not in frames or cam_id not in proj_models:
                        continue
                    cam_data = calibration.cameras[cam_id]
                    img_w, img_h = cam_data.image_size

                    # OBB labels for fish visible in this camera view
                    obb_lines: list[str] = []
                    for _fid, midline in (fish_dict or {}).items():
                        result = _project_raw_points(
                            midline=midline,
                            projection_model=proj_models[cam_id],
                            img_w=img_w,
                            img_h=img_h,
                            lateral_ratio=lateral_ratio,
                            min_visible_keypoints=min_visible,
                        )
                        if result is not None:
                            obb_lines.append(
                                " ".join(str(v) for v in result["obb_line"])
                            )

                    stem = f"{frame_idx:06d}_{cam_id}_trk{ex.track_id}"
                    cv2.imwrite(str(img_dir / f"{stem}.jpg"), frames[cam_id])
                    (lbl_dir / f"{stem}.txt").write_text(
                        "\n".join(obb_lines) + "\n" if obb_lines else ""
                    )
                    n_written["tracking_gaps"] += 1

            # --- low_cameras: one random gap camera per example ---
            if "low_cameras" in cats_for_frame:
                import random

                img_dir, lbl_dir = cat_dirs["low_cameras"]
                for ex in cats_for_frame["low_cameras"]:
                    # Pick one random gap camera for this example
                    available = [
                        c
                        for c in ex.visible_gap_cameras
                        if c in frames and c in proj_models
                    ]
                    if not available:
                        continue
                    cam_id = random.choice(available)
                    cam_data = calibration.cameras[cam_id]
                    img_w, img_h = cam_data.image_size

                    # OBB labels for fish visible in this view
                    obb_lines = []
                    for _fid, midline in (fish_dict or {}).items():
                        result = _project_raw_points(
                            midline=midline,
                            projection_model=proj_models[cam_id],
                            img_w=img_w,
                            img_h=img_h,
                            lateral_ratio=lateral_ratio,
                            min_visible_keypoints=min_visible,
                        )
                        if result is not None:
                            obb_lines.append(
                                " ".join(str(v) for v in result["obb_line"])
                            )

                    stem = f"{frame_idx:06d}_{cam_id}_fish{ex.fish_id:02d}"
                    cv2.imwrite(str(img_dir / f"{stem}.jpg"), frames[cam_id])
                    (lbl_dir / f"{stem}.txt").write_text(
                        "\n".join(obb_lines) + "\n" if obb_lines else ""
                    )
                    n_written["low_cameras"] += 1

            # --- high_curvature / high_residual: one crop per example ---
            for pose_cat in ("high_curvature", "high_residual"):
                if pose_cat not in cats_for_frame:
                    continue
                img_dir, lbl_dir = cat_dirs[pose_cat]

                for ex in cats_for_frame[pose_cat]:
                    # Find a camera where this fish projects successfully
                    import random

                    shuffled_cams = list(all_camera_ids)
                    random.shuffle(shuffled_cams)
                    for cam_id in shuffled_cams:
                        if cam_id not in frames or cam_id not in proj_models:
                            continue
                        cam_data = calibration.cameras[cam_id]
                        img_w, img_h = cam_data.image_size

                        midline = (fish_dict or {}).get(ex.fish_id)
                        if midline is None:
                            continue
                        result = _project_raw_points(
                            midline=midline,
                            projection_model=proj_models[cam_id],
                            img_w=img_w,
                            img_h=img_h,
                            lateral_ratio=lateral_ratio,
                            min_visible_keypoints=min_visible,
                        )
                        if result is None or "pose_line" not in result:
                            continue

                        fish_data = [
                            {
                                "keypoints_2d": result["keypoints_2d"],
                                "visibility": result["visibility"],
                                "lateral_pad": result["lateral_pad"],
                                "fish_id": int(ex.fish_id),
                            }
                        ]
                        _write_pose_crops(
                            frame=frames[cam_id],
                            fish_data_list=fish_data,
                            frame_idx=frame_idx,
                            cam_id=cam_id,
                            crop_w=crop_width,
                            crop_h=crop_height,
                            pose_images_dir=img_dir,
                            pose_labels_dir=lbl_dir,
                            min_visible=min_visible,
                        )
                        n_written[pose_cat] += 1
                        break  # one crop per example

    # 10. Write manifests and dataset.yaml
    for cat in active:
        cat_dir = hard_dir / cat
        if cat in ("tracking_gaps", "low_cameras"):
            _write_obb_dataset_yaml(cat_dir)
        else:
            _write_pose_dataset_yaml(cat_dir, n_keypoints)

    _write_mine_hard_manifests(
        hard_dir,
        tracking_gap_examples,
        low_cameras_examples,
        high_curvature_examples,
        high_residual_examples,
        active,
        temporal_step,
        curv_thresh,
        resid_thresh,
        max_cameras,
        min_gap_length,
    )

    # 11. Summary
    click.echo("\nResults:")
    for cat in sorted(active):
        cat_dir = hard_dir / cat
        click.echo(f"  {cat}: {n_written.get(cat, 0)} images -> {cat_dir}")


def _project_raw_points(
    midline: object,
    projection_model: object,
    img_w: int,
    img_h: int,
    lateral_ratio: float,
    min_visible_keypoints: int = 2,
    edge_factor: float = 2.0,
) -> dict | None:
    """Project raw 3D keypoints to 2D and generate OBB/pose label data.

    Unlike :func:`generate_fish_labels`, this works with raw-keypoint mode
    (no spline fitting required). Projects ``midline.points`` directly.

    Returns:
        Dict with ``obb_line``, ``keypoints_2d``, ``visibility``,
        ``lateral_pad``, and optionally ``pose_line``; or None on failure.
    """
    import torch

    from aquapose.training.geometry import (
        compute_arc_length as _compute_arc_length,
    )
    from aquapose.training.geometry import (
        extrapolate_edge_keypoints as _extrapolate_edge,
    )
    from aquapose.training.geometry import (
        format_obb_annotation as _format_obb,
    )
    from aquapose.training.geometry import (
        format_pose_annotation as _format_pose,
    )
    from aquapose.training.geometry import (
        pca_obb as _pca_obb,
    )

    pts = midline.points  # type: ignore[union-attr]
    if pts is None:
        return None

    # Filter out NaN points
    valid_mask = ~np.isnan(pts[:, 0])
    if valid_mask.sum() < 2:
        return None

    # Project all points
    pts_tensor = torch.from_numpy(pts).float()
    pixels_t, proj_valid = projection_model.project(pts_tensor)  # type: ignore[union-attr]
    pixels = pixels_t.cpu().detach().numpy().astype(np.float64)
    visibility = proj_valid.cpu().detach().numpy().astype(bool) & valid_mask

    # Mark out-of-bounds as invisible
    oob = (
        (pixels[:, 0] < 0)
        | (pixels[:, 0] >= img_w)
        | (pixels[:, 1] < 0)
        | (pixels[:, 1] >= img_h)
    )
    visibility = visibility & ~oob

    n_visible = int(visibility.sum())
    if n_visible < 2:
        return None

    arc_length = _compute_arc_length(pixels, visibility)
    lateral_pad = max(arc_length * lateral_ratio, 5.0)

    kp_ext, vis_ext = _extrapolate_edge(
        pixels, visibility, img_w, img_h, lateral_pad, edge_factor
    )

    obb_corners = _pca_obb(kp_ext, vis_ext, lateral_pad)
    obb_line = _format_obb(obb_corners, img_w, img_h)

    result: dict = {
        "obb_line": obb_line,
        "keypoints_2d": pixels,
        "visibility": visibility,
        "lateral_pad": lateral_pad,
    }

    if n_visible >= min_visible_keypoints:
        x_min, y_min = obb_corners.min(axis=0)
        x_max, y_max = obb_corners.max(axis=0)
        cx = (x_min + x_max) / 2.0 / img_w
        cy = (y_min + y_max) / 2.0 / img_h
        bw = (x_max - x_min) / img_w
        bh = (y_max - y_min) / img_h
        result["pose_line"] = _format_pose(
            cx, cy, bw, bh, pixels, visibility, img_w, img_h
        )

    return result


def _write_mine_hard_manifests(
    hard_dir: Path,
    tracking_gap_examples: list,
    low_cameras_examples: list,
    high_curvature_examples: list,
    high_residual_examples: list,
    active: set[str],
    temporal_step: int,
    curv_thresh: float,
    resid_thresh: float,
    max_cameras: int,
    min_gap_length: int,
) -> None:
    """Write manifest.json for each active hard-mining category."""
    if "tracking_gaps" in active:
        manifest = {
            "category": "tracking_gaps",
            "n_examples": len(tracking_gap_examples),
            "selection_criteria": {
                "min_gap_length": min_gap_length,
                "temporal_step": temporal_step,
            },
            "examples": [
                {
                    "frame_idx": ex.frame_idx,
                    "camera_id": ex.camera_id,
                    "track_id": ex.track_id,
                    "gap_length": ex.gap_length,
                }
                for ex in tracking_gap_examples
            ],
        }
        (hard_dir / "tracking_gaps" / "manifest.json").write_text(
            json.dumps(manifest, indent=2), encoding="utf-8"
        )

    if "low_cameras" in active:
        manifest = {
            "category": "low_cameras",
            "n_examples": len(low_cameras_examples),
            "selection_criteria": {
                "max_cameras": max_cameras,
                "temporal_step": temporal_step,
            },
            "examples": [
                {
                    "frame_idx": ex.frame_idx,
                    "fish_id": ex.fish_id,
                    "n_cameras": ex.n_cameras,
                    "contributing_cameras": ex.contributing_cameras,
                    "visible_gap_cameras": ex.visible_gap_cameras,
                }
                for ex in low_cameras_examples
            ],
        }
        (hard_dir / "low_cameras" / "manifest.json").write_text(
            json.dumps(manifest, indent=2), encoding="utf-8"
        )

    if "high_curvature" in active:
        manifest = {
            "category": "high_curvature",
            "n_examples": len(high_curvature_examples),
            "selection_criteria": {
                "curvature_threshold": curv_thresh,
                "temporal_step": temporal_step,
            },
            "examples": [
                {
                    "frame_idx": ex.frame_idx,
                    "fish_id": ex.fish_id,
                    "curvature": round(ex.curvature, 6),
                }
                for ex in high_curvature_examples
            ],
        }
        (hard_dir / "high_curvature" / "manifest.json").write_text(
            json.dumps(manifest, indent=2), encoding="utf-8"
        )

    if "high_residual" in active:
        manifest = {
            "category": "high_residual",
            "n_examples": len(high_residual_examples),
            "selection_criteria": {
                "residual_threshold": resid_thresh,
                "temporal_step": temporal_step,
            },
            "examples": [
                {
                    "frame_idx": ex.frame_idx,
                    "fish_id": ex.fish_id,
                    "mean_residual": round(ex.mean_residual, 4),
                    "n_cameras": ex.n_cameras,
                }
                for ex in high_residual_examples
            ],
        }
        (hard_dir / "high_residual" / "manifest.json").write_text(
            json.dumps(manifest, indent=2), encoding="utf-8"
        )


@pseudo_label_group.command("select")
@click.argument("run", default=None, required=False)
@click.option(
    "--pseudo-dir",
    default=None,
    type=click.Path(exists=True, path_type=Path),
    help="Pseudo-label directory. Overrides run resolution.",
)
@click.option(
    "--output-dir",
    required=True,
    type=click.Path(path_type=Path),
    help="Output directory for selected subset.",
)
@click.option(
    "--obb-target",
    type=int,
    default=50,
    show_default=True,
    help="Target number of OBB images.",
)
@click.option(
    "--pose-target",
    type=int,
    default=320,
    show_default=True,
    help="Target number of pose crops.",
)
@click.option(
    "--val-fraction",
    type=float,
    default=0.2,
    show_default=True,
    help="Fraction of pose crops for secondary val set.",
)
@click.option(
    "--labelstudio-prefix",
    default=None,
    type=str,
    help=(
        "Generate Label Studio pre-annotation JSON. Value is the URL prefix "
        "from the document root, e.g. 'round1_selected'. Output images/ path "
        "is appended automatically."
    ),
)
@click.pass_context
def select(
    ctx: click.Context,
    run: str | None,
    pseudo_dir: Path | None,
    output_dir: Path,
    obb_target: int,
    pose_target: int,
    val_fraction: float,
    labelstudio_prefix: str | None,
) -> None:
    """Select a diversity-maximizing subset from generated pseudo-labels.

    Uses 3-axis sampling for OBB (camera, temporal, fish-count) and 2-axis
    sampling for pose (camera, 2D curvature). Pose crops are split into
    train/val by temporal ordering.
    """
    from aquapose.training.select_diverse_subset import (
        select_obb_subset,
        select_pose_subset,
    )

    if pseudo_dir is None:
        from aquapose.cli_utils import get_project_dir, resolve_run

        run_dir = resolve_run(run, get_project_dir(ctx))
        pseudo_dir = run_dir / "pseudo_labels"

    if not pseudo_dir.exists():
        raise click.ClickException(f"Pseudo-label directory not found: {pseudo_dir}")

    # OBB selection
    obb_src = pseudo_dir / "obb"
    if (obb_src / "confidence.json").exists():
        click.echo(
            f"Selecting ~{obb_target} OBB images (val_fraction={val_fraction})..."
        )
        obb_stats = select_obb_subset(
            pseudo_dir, output_dir / "obb", obb_target, val_fraction
        )
        click.echo(
            f"  OBB: {obb_stats['total_selected']}/{obb_stats['total_available']} "
            f"selected (train={obb_stats['train_count']}, val={obb_stats['val_count']})"
        )
        click.echo(f"  Across {obb_stats['n_cameras']} cameras:")
        for cam_id, count in sorted(obb_stats["per_camera"].items()):
            click.echo(f"    {cam_id}: {count}")
        if labelstudio_prefix is not None:
            from aquapose.training.labelstudio_export import export_labelstudio_json

            prefix = f"/data/local-files/?d={labelstudio_prefix}/obb/images/"
            obb_out = output_dir / "obb" / "labelstudio.json"
            n_tasks = export_labelstudio_json(
                output_dir / "obb", obb_out, "obb", image_url_prefix=prefix
            )
            click.echo(f"  Label Studio JSON: {obb_out} ({n_tasks} tasks)")
    else:
        click.echo("No OBB confidence.json found, skipping OBB selection.")

    # Pose selection
    pose_src = pseudo_dir / "pose" / "consensus"
    if (pose_src / "confidence.json").exists():
        click.echo(
            f"\nSelecting ~{pose_target} pose crops (val_fraction={val_fraction})..."
        )
        pose_stats = select_pose_subset(
            pseudo_dir, output_dir / "pose", pose_target, val_fraction
        )
        click.echo(
            f"  Pose: {pose_stats['total_selected']}/{pose_stats['total_available']} "
            f"selected (train={pose_stats['train_count']}, val={pose_stats['val_count']})"
        )
        click.echo(f"  Curvature quartiles: {pose_stats['curvature_quartiles']}")
        click.echo("  Per curvature bin:")
        for bin_id, count in sorted(pose_stats["per_curvature_bin"].items()):
            click.echo(f"    Q{bin_id}: {count}")
        click.echo("  Per camera:")
        for cam_id, count in sorted(pose_stats["per_camera"].items()):
            click.echo(f"    {cam_id}: {count}")

        # Write dataset.yaml with kpt_names for downstream tools
        from aquapose.training.coco_convert import KEYPOINT_NAMES

        pose_yaml = {
            "names": {0: "fish"},
            "kpt_shape": [len(KEYPOINT_NAMES), 3],
            "kpt_names": list(KEYPOINT_NAMES),
        }
        import yaml

        (output_dir / "pose" / "dataset.yaml").write_text(
            yaml.dump(pose_yaml, default_flow_style=False)
        )

        if labelstudio_prefix is not None:
            from aquapose.training.labelstudio_export import export_labelstudio_json

            prefix = f"/data/local-files/?d={labelstudio_prefix}/pose/images/"
            pose_out = output_dir / "pose" / "labelstudio.json"
            n_tasks = export_labelstudio_json(
                output_dir / "pose",
                pose_out,
                "pose",
                image_url_prefix=prefix,
            )
            click.echo(f"  Label Studio JSON: {pose_out} ({n_tasks} tasks)")
    else:
        click.echo("No pose consensus confidence.json found, skipping pose selection.")

    click.echo(f"\nOutput: {output_dir}")


@pseudo_label_group.command("from-labelstudio")
@click.argument("json_path", type=click.Path(exists=True, path_type=Path))
@click.option(
    "--output-dir",
    required=True,
    type=click.Path(path_type=Path),
    help="Output YOLO-format directory (images/ and labels/).",
)
@click.option(
    "-t",
    "--task",
    required=True,
    type=click.Choice(["obb", "pose"]),
    help="YOLO task type.",
)
@click.option(
    "--images-dir",
    default=None,
    type=click.Path(exists=True, path_type=Path),
    help="Directory containing original images. Searches train/ and val/ subdirs.",
)
@click.option(
    "--num-kpts",
    type=int,
    default=6,
    show_default=True,
    help="Number of keypoints (pose only).",
)
def from_labelstudio(
    json_path: Path,
    output_dir: Path,
    task: str,
    images_dir: Path | None,
    num_kpts: int,
) -> None:
    """Convert a Label Studio JSON export back to YOLO format.

    The output directory can be passed directly to ``data import --input-dir``
    with ``--source corrected``.
    """
    from aquapose.training.labelstudio_import import import_labelstudio_json

    stats = import_labelstudio_json(
        json_path,
        output_dir,
        task,
        images_dir=images_dir,
        num_kpts=num_kpts,
    )
    click.echo(
        f"Converted {stats['tasks_converted']} tasks "
        f"({stats['total_annotations']} annotations, "
        f"{stats['skipped']} skipped)"
    )
    click.echo(f"Output: {output_dir}")


@pseudo_label_group.command("inspect")
@click.argument("run", default=None, required=False)
@click.option(
    "--input-dir",
    default=None,
    type=click.Path(exists=True, path_type=Path),
    help="Inspect an arbitrary directory (with images/train/ + labels/train/) instead of a run.",
)
@click.option(
    "--output-dir",
    default=None,
    type=click.Path(),
    help="Output directory for annotated PNGs. Defaults to {run_dir}/pseudo_labels/viz/ or {input_dir}/viz/.",
)
@click.option(
    "-n",
    "n_samples",
    default=None,
    type=int,
    help="Number of images to sample randomly per subset. Omit to inspect all.",
)
@click.option(
    "--seed",
    default=42,
    type=int,
    show_default=True,
    help="Random seed for sampling.",
)
@click.pass_context
def inspect(
    ctx: click.Context,
    run: str | None,
    input_dir: Path | None,
    output_dir: str | None,
    n_samples: int | None,
    seed: int,
) -> None:
    """Visualize pseudo-label outputs from a pipeline run or arbitrary directory.

    When ``--input-dir`` is provided, inspects that single directory directly
    (must contain ``images/train/`` and ``labels/train/``). Otherwise resolves
    a pipeline run and inspects all pseudo-label subsets.
    """
    if input_dir is not None:
        # Single directory mode — inspect all splits (train, val)
        base_out = Path(output_dir) if output_dir else input_dir / "viz"
        total = 0
        for split in ("train", "val"):
            if (input_dir / "images" / split).exists():
                count = _inspect_subset(
                    input_dir, base_out / split, n_samples, seed, split=split
                )
                total += count
        if total == 0:
            # Fallback: try without split subdirectory
            total = _inspect_subset(input_dir, base_out, n_samples, seed)
        click.echo(f"Wrote {total} annotated images to {base_out}")
        return

    from aquapose.cli_utils import get_project_dir, resolve_run

    run_dir = resolve_run(run, get_project_dir(ctx))
    pseudo_dir = run_dir / "pseudo_labels"
    if not pseudo_dir.exists():
        raise click.ClickException(
            f"No pseudo_labels/ directory found in {run_dir}. "
            "Run 'aquapose pseudo-label generate' first."
        )

    base_out = Path(output_dir) if output_dir else pseudo_dir / "viz"

    # Discover all pseudo-label subsets to inspect
    inspect_targets: list[tuple[Path, Path]] = []
    for candidate, viz_subdir in [
        (pseudo_dir / "obb", base_out / "obb"),
        (pseudo_dir / "pose" / "consensus", base_out / "pose" / "consensus"),
        (pseudo_dir / "pose" / "gap", base_out / "pose" / "gap"),
    ]:
        images_check = candidate / "images" / "train"
        if images_check.exists() and any(images_check.iterdir()):
            inspect_targets.append((candidate, viz_subdir))

    if not inspect_targets:
        raise click.ClickException(
            f"No pseudo-label image directories found in {pseudo_dir}"
        )

    total_written = 0
    for data_path, out_path in inspect_targets:
        count = _inspect_subset(data_path, out_path, n_samples, seed)
        total_written += count

    click.echo(f"Wrote {total_written} annotated images to {base_out}")


def _inspect_subset(
    data_path: Path,
    out_path: Path,
    n_samples: int | None,
    seed: int,
    split: str | None = None,
) -> int:
    """Inspect a single pseudo-label subset directory.

    Args:
        data_path: YOLO-format directory containing images/ and labels/.
        out_path: Output directory for annotated PNGs.
        n_samples: Number of images to sample randomly. None for all.
        seed: Random seed for sampling.
        split: Specific split to inspect ("train", "val"). If None, tries
            "train" then falls back to flat images/.

    Returns:
        Number of images written.
    """
    import random

    out_path.mkdir(parents=True, exist_ok=True)

    # Find image/label directories
    if split is not None:
        images_dir = data_path / "images" / split
        labels_dir = data_path / "labels" / split
    else:
        images_dir = data_path / "images" / "train"
        labels_dir = data_path / "labels" / "train"
        if not images_dir.exists():
            images_dir = data_path / "images"
        if not labels_dir.exists():
            labels_dir = data_path / "labels"

    if not images_dir.exists() or not labels_dir.exists():
        return 0

    # Collect image files that have matching label files
    image_files = sorted(
        p
        for p in images_dir.iterdir()
        if p.suffix.lower() in {".jpg", ".jpeg", ".png"}
        and (labels_dir / f"{p.stem}.txt").exists()
    )

    if not image_files:
        return 0

    # Sample if requested
    if n_samples is not None and n_samples < len(image_files):
        rng = random.Random(seed)
        image_files = rng.sample(image_files, n_samples)

    # Load confidence sidecar if available
    confidence_data: dict = {}
    for candidate in [
        data_path / "confidence.json",
        data_path.parent / "confidence.json",
    ]:
        if candidate.exists():
            confidence_data = json.loads(candidate.read_text())
            break

    # Detect label type from first label file
    first_label = (labels_dir / f"{image_files[0].stem}.txt").read_text().strip()
    first_tokens = first_label.split("\n")[0].split()
    is_obb = len(first_tokens) == 9  # cls + 4 corners x 2

    subset_name = data_path.relative_to(data_path.parent.parent)
    click.echo(
        f"Inspecting {len(image_files)} images from {subset_name} "
        f"({'OBB' if is_obb else 'pose'} labels)"
    )

    for img_path in image_files:
        image = cv2.imread(str(img_path))
        if image is None:
            logger.warning("Failed to read %s, skipping", img_path)
            continue

        img_h, img_w = image.shape[:2]
        label_path = labels_dir / f"{img_path.stem}.txt"
        label_text = label_path.read_text().strip()

        if not label_text:
            continue

        # Look up confidence metadata
        conf_entry = confidence_data.get(img_path.stem, {})
        fish_labels = conf_entry.get("labels", [])

        for line_idx, line in enumerate(label_text.split("\n")):
            tokens = line.split()
            if not tokens:
                continue

            # Get per-fish metadata if available
            fish_meta = fish_labels[line_idx] if line_idx < len(fish_labels) else {}
            confidence = fish_meta.get("confidence")
            gap_reason = fish_meta.get("gap_reason")

            if is_obb:
                _draw_obb_inspection(image, tokens, img_w, img_h)
            else:
                _draw_pose_inspection(image, tokens, img_w, img_h)

            # Build text overlay
            text_parts: list[str] = []
            if confidence is not None:
                text_parts.append(f"conf={confidence:.2f}")
            source = fish_meta.get("source")
            if source is not None:
                text_parts.append(source)
            elif gap_reason is not None:
                text_parts.append(f"gap:{gap_reason}")
            elif fish_meta:
                text_parts.append("consensus")

            if text_parts:
                text = " | ".join(text_parts)
                # Position text near the annotation
                if is_obb:
                    tx = int(float(tokens[1]) * img_w)
                    ty = max(15, int(float(tokens[2]) * img_h) - 10)
                else:
                    tx = max(
                        5, int(float(tokens[1]) * img_w - float(tokens[3]) * img_w / 2)
                    )
                    ty = max(
                        15,
                        int(float(tokens[2]) * img_h - float(tokens[4]) * img_h / 2)
                        - 10,
                    )

                cv2.putText(
                    image,
                    text,
                    (tx, ty),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.45,
                    (255, 255, 255),
                    2,
                )
                cv2.putText(
                    image,
                    text,
                    (tx, ty),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.45,
                    (0, 200, 0),
                    1,
                )

        cv2.imwrite(str(out_path / f"{img_path.stem}.png"), image)

    return len(image_files)


def _draw_obb_inspection(
    image: np.ndarray,
    tokens: list[str],
    img_w: int,
    img_h: int,
) -> None:
    """Draw an OBB polygon from a YOLO-OBB label line."""
    # tokens: cls x1 y1 x2 y2 x3 y3 x4 y4 (normalized)
    corners = np.array(
        [
            [float(tokens[1]) * img_w, float(tokens[2]) * img_h],
            [float(tokens[3]) * img_w, float(tokens[4]) * img_h],
            [float(tokens[5]) * img_w, float(tokens[6]) * img_h],
            [float(tokens[7]) * img_w, float(tokens[8]) * img_h],
        ],
        dtype=np.int32,
    )
    cv2.polylines(image, [corners.reshape(-1, 1, 2)], True, (0, 255, 0), 2)


def _draw_pose_inspection(
    image: np.ndarray,
    tokens: list[str],
    img_w: int,
    img_h: int,
) -> None:
    """Draw a pose bbox and keypoints from a YOLO-Pose label line."""
    # tokens: cls cx cy w h x1 y1 v1 x2 y2 v2 ...
    cx = float(tokens[1]) * img_w
    cy = float(tokens[2]) * img_h
    bw = float(tokens[3]) * img_w
    bh = float(tokens[4]) * img_h
    x1 = int(cx - bw / 2)
    y1 = int(cy - bh / 2)
    x2 = int(cx + bw / 2)
    y2 = int(cy + bh / 2)
    cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)

    # Draw keypoints
    kp_tokens = tokens[5:]
    for i in range(0, len(kp_tokens), 3):
        if i + 2 >= len(kp_tokens):
            break
        kx = float(kp_tokens[i]) * img_w
        ky = float(kp_tokens[i + 1]) * img_h
        vis = int(float(kp_tokens[i + 2]))
        if vis > 0:
            color = (0, 0, 255) if i == 0 else (0, 255, 0)
            cv2.circle(image, (int(kx), int(ky)), 4, color, -1)
